### ISSUE TITLE
Failed to setup Midpoint demo

### ISSUE THREAD

**Issue by ebz-jeaanmichel** [Evolveum/midpoint-kubernetes#2]
Hello,

I'm trying to setup Midpoint Demo on a VM Ubuntu Server 22.04, but I continue getting the following error:

`error: unable to find field "spec.template.spec.volumes.[name=nfs-volume].nfs.server" in replacement target`

I don't have much experience in K8s, and it is kind difficult for me to debug.

Could you please help to find the cause for this error?

My environment:
```
kubectl version --output=yaml
clientVersion:
  buildDate: "2023-08-29T21:26:58Z"
  compiler: gc
  gitCommit: 8dc49c4b984b897d423aab4971090e1879eb4f23
  gitTreeState: clean
  gitVersion: v1.28.1
  goVersion: go1.20.7
  major: "1"
  minor: "28"
  platform: linux/amd64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
serverVersion:
  buildDate: "2023-08-29T21:27:47Z"
  compiler: gc
  gitCommit: 8dc49c4b984b897d423aab4971090e1879eb4f23
  gitTreeState: clean
  gitVersion: v1.28.1
  goVersion: go1.20.7
  major: "1"
  minor: "28"
  platform: linux/amd64

Linux midpoint-demo 5.15.0-84-generic #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

If you need more informations about the environment, please let me know.

Thank you in advance.
